name: "Hello world workflow"
# this will trigger workflow on psh doe master bbranch
on:
    push:
        braches:
            -master
            -production


jobs:
    hello_world:
        runs-on: ubantu-latest
        steps:
       - name:"print Hello world"
         run: echo "hello world"